### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AtieP** [AtieP/dpyjs-bot#1]
- [ ] Bad word filter (bot/cogs/filter.py)
- [x] Server and user information (bot/cogs/information.py)
- [x] Color on tag and welcome embed
- [x] When executing `infrs` command and the target user has no infractions, avoid raising a Discord error
